name: 'Netlify Analytics Collector'
description: 'Fetches netlify analytics and uploads it to artifacts.'
author: 'NiklasMerz'
inputs: 
  netlify-site-id:
    description: 'You can get the id for your netlify site by looking at the devtools'
    required: true
  netlify-token:
    description: 'Personal access token from your netlify account'
    required: true
  days:
    description: 'How many days back from today should be fetched. Netlify stores analytics for about 30 days.'
    default: '29'
    required: false
  disable-header:
    description: 'Set to true for appending to CSV files and if no header is necessary'
    default: 'false'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'